# Generated by Django 4.2.1 on 2023-06-08 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_herramientas_productodestacados_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Herramientas',
            new_name='Herramienta',
        ),
        migrations.RenameModel(
            old_name='ProductoDestacados',
            new_name='Productodestacado',
        ),
    ]
