# Generated by Django 4.2.1 on 2023-06-19 06:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_venta_detalleventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='total',
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productodestacado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 2, 35, 0, 409364)),
        ),
    ]
