# Generated by Django 4.1.5 on 2023-06-22 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_venta_estado_alter_venta_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 22, 16, 43, 46, 429267)
            ),
        ),
    ]
