# Generated by Django 4.1.5 on 2023-06-22 21:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_venta_fecha"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Herramienta",
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.CharField(default="destacado", max_length=20),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.producto"
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 22, 17, 6, 36, 944496)
            ),
        ),
        migrations.DeleteModel(
            name="Productodestacado",
        ),
    ]
