# Generated by Django 4.1.5 on 2023-06-22 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_delete_herramienta_producto_categoria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="destacado",
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.CharField(default="semilla", max_length=20),
        ),
        migrations.AlterField(
            model_name="venta",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 22, 17, 8, 39, 553641)
            ),
        ),
    ]
