# Generated by Django 4.1.5 on 2023-06-22 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_producto_destacado_alter_producto_categoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="destacado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="venta",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 22, 17, 9, 11, 762085)
            ),
        ),
    ]
